lint:
  directories:
    exclude:
      - .vscode
      - backend
      - frontend

  rules:
    remove:
      - MAX_LINE_LENGTH

  rules_option:
    indent:
      style: 4
      not_insert_newline: true

    quote_consistent:
      quote: double

    enum_field_names_zero_value_end_with:
      suffix: UNSPECIFIED

    service_names_end_with:
      text: Service
